import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  ...compat.extends("next/core-web-vitals", "next/typescript"),
  {
    // next-env.d.ts is generated by Next on every dev/build run.
    ignores: [".next/**", "node_modules/**", "supabase/bundle/**", "next-env.d.ts"],
  },
];

export default config;
